services:
  dev-container:
    build:
      target: dev-container
    image: fpts:dev-container
    container_name: fpts-dev-container
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    tty: true

volumes:
  node-modules:
