on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Restore npm cache
        id: npm-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Save npm cache
        uses: actions/cache/save@v3
        with:
          path: ~/.npm
          key: ${{ steps.npm-cache-restore.outputs.cache-primary-key }}

      - run: npm run ${{ matrix.job }}

